name: Deploy Flask app

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2.3.2
      with:
        python-version: '3.x'    
    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt
    - name: Start Flask app
      run: |
        source env/bin/activate
        gunicorn app:app --bind 0.0.0.0:${{ env.PORT }}
        env:
            PORT: ${{ github.event.inputs.port }}
